### ISSUE TITLE
sync button and sync setting on login screen

### ISSUE THREAD

**Issue by xyb994** [ole-vi/takeout#71]
An issue was brought up in https://github.com/ole-vi/takeout/pull/65#issuecomment-397030934 and https://github.com/ole-vi/takeout/pull/65#issuecomment-397309669.

**Comment by aakarnik** [comment]
Currently, I will work on moving the settings from the sync icon to the settings :)

**Comment by aakarnik** [comment]
The sync button will just be a rotating refresh button. Hitting the icon will allow the user to sync once.

Rest of the settings for sync will be moved under the settings tab. The settings tab will include the auto-sync option. The three buttons on the pop-up will be: `save`, `cancel`, and `sync` (instead of `connect`).

**Comment by leomaxi** [comment]
Exactly @aakarnik .. Proceed with it
